// Copyright 2026 Project Maintainers
// SPDX-License-Identifier: Apache-2.0
import assert from'node:assert/strict';import test from'node:test';import{readFileSync,mkdtempSync,readdirSync,mkdirSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{expectedNotificationAckResult,assertNotificationAckReceipt}from'../notification-ack-contract.mjs';
const source='a'.repeat(40),receipt=()=>({kind:'actual-bundle-native-notification-ack',bundleSource:source,profile:'isolated-synthetic-profile',externalAttempts:0,result:expectedNotificationAckResult()});
function leaves(value,path=[]){return value&&typeof value==='object'?Object.entries(value).flatMap(([key,v])=>leaves(v,[...path,key])):[path];}
test('complete acknowledgement receipt distinguishes confirmed drain from permanent quarantine',()=>{assertNotificationAckReceipt(receipt(),source);assert.equal(receipt().result.rows.filter(r=>r.drainingScopes===1).length,4);assert.equal(receipt().result.rows.filter(r=>r.confirmedDrainResumes).length,2);});
test('every acknowledgement result field is mandatory and exact',()=>{for(const path of leaves(receipt().result)){for(const mode of ['alter','delete']){const r=receipt();let parent=r.result;for(const key of path.slice(0,-1))parent=parent[key];const key=path.at(-1),value=parent[key];if(mode==='delete')delete parent[key];else parent[key]=typeof value==='boolean'?!value:typeof value==='number'?value+1:value+' changed';assert.throws(()=>assertNotificationAckReceipt(r,source),path.join('.'));}}});
test('refuse partial, duplicate, extra, foreign-source and falsely cleaned acknowledgement receipts',()=>{for(const change of [r=>r.result.rows.pop(),r=>r.result.rows.reverse(),r=>r.result.rows.push(r.result.rows[0]),r=>r.result.rows[1].drainingScopes=0,r=>r.result.extra=true,r=>r.extra=true,r=>r.bundleSource='b'.repeat(40),r=>r.profile='',r=>r.externalAttempts=1,r=>r.kind='source-only',r=>r.result.scenarios=1]){const r=receipt();change(r);assert.throws(()=>assertNotificationAckReceipt(r,source));}for(const key of Object.keys(receipt())){const r=receipt();delete r[key];assert.throws(()=>assertNotificationAckReceipt(r,source));}});
test('acknowledgement cohort isolates before SDK and validates exact receipts before private write',()=>{const s=readFileSync(new URL('../accept-notification-ack.mjs',import.meta.url),'utf8');assert.ok(s.indexOf('Object.assign(process.env,env)')<s.indexOf('const sdk=await import'));assert.ok(s.indexOf('assertNotificationAckReceipt(receipt,manifest.sourceCommit)')<s.indexOf("join(directory,'acceptance.json')"));assert.match(s,/await verifyCuration\(bundle/);assert.match(s,/additionalExtensionPaths:\[join\(bundle,'extensions\/openai-compatibility\/index.ts'\)\]/);assert.match(s,/runtime\.checkAuth=async/);assert.match(s,/runtime\.getAuth=async/);assert.match(s,/allowModelNetwork:false,refreshOnCreate:false/);assert.match(s,/Actual bundle changed during acknowledgement cohort/);assert.match(s,/mode==='confirm'\?0:1/);assert.doesNotMatch(s,/setAutoCompactionEnabled\(false\)/);});
test('acknowledgement failure injection follows the real publisher, never a metadata-minted scope',()=>{const s=readFileSync(new URL('../notification-acknowledgement.mjs',import.meta.url),'utf8');assert.ok(s.indexOf('await original.apply(session.agent,args)')<s.indexOf('await ack.promise'));assert.match(s,/session\.agent\.abort\(\)/);assert.match(s,/assert\.equal\(finalized,false\)/);assert.match(s,/scopeCleanup,'unconfirmed'/);assert.match(s,/scope admission unavailable\|cleanup incomplete/);assert.match(s,/assert\.equal\(observation\.effects,1\)/);assert.doesNotMatch(s,/scope\.close\s*=|runtimeFactory|new ToolScopeRegistry|triggerTurn:true/);});
test('acknowledgement helper preserves primary, restoration and observation-write failures',async()=>{const {exerciseNotificationAcknowledgement}=await import('../notification-acknowledgement.mjs'),cwd=mkdtempSync(join(tmpdir(),'ack-cleanup-control-')),primary=Error('synthetic assignment failure'),restoration=Error('synthetic restore failure');let off=false,passed=false;const original=async()=>true,target={streamFunction:()=>{},notifyToolOutput:original,subscribe:()=>{for(const dir of readdirSync(cwd))mkdirSync(join(cwd,dir,'observations.json'));return()=>{off=true;};}},agent=new Proxy(target,{set(o,key,value){if(key==='notifyToolOutput')throw primary;o[key]=value;return true;},defineProperty(o,key,d){if(key==='streamFunction')throw restoration;return Reflect.defineProperty(o,key,d);}});
 try{await assert.rejects(exerciseNotificationAcknowledgement({agent,model:{api:'openai-responses'}},()=>{},cwd,'confirm'),e=>{assert.ok(e instanceof AggregateError);assert.equal(e.errors.length,3);assert.equal(e.errors[0],primary);assert.equal(e.errors[1],restoration);assert.equal(typeof e.errors[2].code,'string');return true;});assert.equal(off,true);assert.equal(target.notifyToolOutput,original);passed=true;}finally{if(passed)rmSync(cwd,{recursive:true,force:true});}
});
