// Copyright 2026 Project Maintainers
// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict';import test from 'node:test';import{readFileSync}from'node:fs';
import{frameProfileReceipt,readProfileReceiptFrames,validateProfileReceipt,PROFILE_RECEIPT_LIMIT}from'../profile-receipt.mjs';import{requireProfileCompletion}from'../accept-profile-framed.mjs';import{syntheticProfileReceipt}from'./fixtures/profile-receipt.mjs';
const identity={source:'a'.repeat(40),bundle:'/synthetic bundle'},raw=()=>Buffer.from(JSON.stringify(syntheticProfileReceipt()));
test('oversized single-line CLI receipt survives bounded framing without changing Unicode or any frame',()=>{const r=syntheticProfileReceipt();r.settingsMenu.frames[7].text+='\n'+('Synthetic 🧭 literal 漢字\n').repeat(5000);const bytes=Buffer.from(JSON.stringify(r));assert.ok(bytes.length>65536);const frames=frameProfileReceipt(bytes,identity);assert.ok(frames.length>1);for(const f of frames)assert.ok(Buffer.byteLength(JSON.stringify(f))<9*1024);assert.deepEqual(readProfileReceiptFrames(frames,identity),r);});
test('framing retains the existing four-MiB child receipt bound',()=>{const bytes=raw(),text=Buffer.concat([bytes,Buffer.alloc(PROFILE_RECEIPT_LIMIT-bytes.length,32)]),frames=frameProfileReceipt(text,identity);assert.deepEqual(readProfileReceiptFrames(frames,identity),syntheticProfileReceipt());assert.throws(()=>frameProfileReceipt(Buffer.concat([text,Buffer.from(' ')]),identity));});
test('reject missing, reordered, duplicated, altered, foreign and noncanonical fragments',()=>{const bytes=Buffer.from(raw().toString().padEnd(20000,' ')),frames=frameProfileReceipt(bytes,identity);for(const mutate of [f=>f.pop(),f=>f.reverse(),f=>f.push(f[0]),f=>f[1].part=0,f=>f[0].parts++,f=>f[0].bytes++,f=>f[0].sha256='b'.repeat(64),f=>f[1].source='b'.repeat(40),f=>f[0].kind='source-only',f=>f[0].extra=true,f=>delete f[0].data,f=>f[0].data+=' ',f=>f[0].data='!'.repeat(8192),f=>f[0].data=f[0].data.slice(4)]){const f=structuredClone(frames);mutate(f);assert.throws(()=>readProfileReceiptFrames(f,identity));}assert.throws(()=>readProfileReceiptFrames([],identity));assert.throws(()=>readProfileReceiptFrames(frames,{...identity,bundle:'foreign'}));});
test('nominal exit zero without a complete valid CLI receipt is failure',()=>{for(const r of[{status:0,signal:null,stdout:Buffer.alloc(0)},{status:0,stdout:Buffer.from('{}')},{status:0,stdout:Buffer.from('{')},{status:1,stdout:raw()},{status:0,error:Error('timeout'),stdout:raw()},{status:0,signal:'SIGTERM',stdout:raw()}])assert.throws(()=>requireProfileCompletion(r,identity));assert.deepEqual(readProfileReceiptFrames(requireProfileCompletion({status:0,signal:null,stdout:raw()},identity),identity),syntheticProfileReceipt());});
test('profile semantics remain mandatory after transport integrity matches',()=>{for(const mutate of [r=>r.status='failed',r=>r.savedContextProfile=false,r=>r.hostedRequests=1,r=>r.credentialsCopied=true,r=>r.settingsMenu.contextSettings.frames.pop(),r=>r.settingsMenu.waitSettings.frames[0].text='lost',r=>r.settingsMenu.frames.pop(),r=>r.extra=true]){const r=syntheticProfileReceipt();mutate(r);assert.throws(()=>validateProfileReceipt(r,identity.bundle));assert.throws(()=>frameProfileReceipt(Buffer.from(JSON.stringify(r)),identity));}assert.throws(()=>frameProfileReceipt(Buffer.from([0xff]),identity));});
test('hosted CLI uses supervised isolated bounded output without widening time or enabling artifact upload',()=>{const s=readFileSync(new URL('../accept-profile-framed.mjs',import.meta.url),'utf8'),workflow=readFileSync(new URL('../../.github/workflows/private-windows-artifacts.yml',import.meta.url),'utf8');assert.match(workflow,/run: node distribution\/accept-profile-framed.mjs '\.pi\/extracted artifact'/);assert.match(workflow,/timeout-minutes: 20/);assert.match(s,/env=isolatedEnvironment/);assert.match(s,/timeout:300000,maxBuffer:PROFILE_RECEIPT_LIMIT/);assert.match(s,/frames=requireProfileCompletion/);assert.match(s,/process\.stdout\.write\(JSON\.stringify\(frame\)/);assert.match(s,/Bundle changed during CLI acceptance/);assert.doesNotMatch(workflow,/path:.*profile-receipt|actions\/deploy|gh release/);});
