import assert from'node:assert/strict';import test from'node:test';import{metadataSource,validateNativeToolMetadata}from'../accept-tool-metadata.mjs';
const rows=()=>['openai-responses','openai-codex-responses'].map(api=>({api,requests:4,nativeRegistryMetadata:true,immutableQuickJSSnapshot:true,nativeWrapperPreserved:true,customInputReplay:true,historyUnchanged:true,inspectionDelegations:0,lookupDelegations:1,activeScopes:0,drainingScopes:0,liveServiceCalls:0}));
test('installed metadata contract requires both original native routes and eight synthetic requests',()=>{const r=validateNativeToolMetadata(rows());assert.equal(r.syntheticModelRequests,8);assert.equal(r.scenarios,4);assert.equal(r.nativeLookupDelegations,2);assert.equal(r.liveServiceCalls,0);});
for(const key of ['nativeRegistryMetadata','immutableQuickJSSnapshot','nativeWrapperPreserved','customInputReplay','historyUnchanged'])test('installed metadata refuses missing '+key,()=>{const r=rows();delete r[0][key];assert.throws(()=>validateNativeToolMetadata(r));});
for(const [key,value]of Object.entries({requests:3,inspectionDelegations:1,lookupDelegations:0,activeScopes:1,drainingScopes:1,liveServiceCalls:1,api:'replacement'}))test('installed metadata refuses changed '+key,()=>{const r=rows();r[1][key]=value;assert.throws(()=>validateNativeToolMetadata(r));});
test('installed metadata refuses missing or reordered provider rows',()=>{assert.throws(()=>validateNativeToolMetadata(rows().slice(1)));assert.throws(()=>validateNativeToolMetadata(rows().reverse()));});
test('synthetic source preserves exact native metadata and separates inspection from native delegation',()=>{const expected=[{name:'read',description:'literal "quote" \\ 雪 🌊'}],inspect=metadataSource(expected,false),delegate=metadataSource(expected,true);assert.ok(inspect.includes(JSON.stringify(expected)));assert.ok(inspect.includes('Object.isFrozen'));assert.ok(inspect.includes('globalThis.ALL_TOOLS=[]'));assert.ok(!inspect.includes('await tools'));assert.ok(delegate.includes('await tools[selected.name]'));assert.ok(delegate.includes('native wrapper changed'));assert.deepEqual(expected,[{name:'read',description:'literal "quote" \\ 雪 🌊'}]);});
test('synthetic metadata source cannot silently exceed the existing source cap',()=>assert.throws(()=>metadataSource([{name:'read',description:'x'.repeat(65536)}],false),/source budget/));

import{findNativeMetadataResult}from'../accept-tool-metadata.mjs';
const nativeMessages=()=>[{role:'assistant',content:[{type:'toolCall',id:'provider_call|native_item',name:'exec',arguments:{code:'text(1)'}}]},{role:'toolResult',toolName:'exec',toolCallId:'provider_call|native_item',content:[{type:'text',text:'literal output'}],isError:false},{role:'assistant',content:[{type:'text',text:'done'}]}];
test('metadata correlates the original native internal ID, not raw provider call_id',()=>{const m=nativeMessages();assert.equal(findNativeMetadataResult(m,'text(1)'),m[1]);});
for(const [label,change]of Object.entries({rawProviderId:m=>m[1].toolCallId='provider_call',foreignId:m=>m[1].toolCallId='other|native_item',differentName:m=>m[1].toolName='read',differentCallName:m=>m[0].content[0].name='read',differentSource:m=>m[0].content[0].arguments.code='text(2)',extraInput:m=>m[0].content[0].arguments.authority=true,missingId:m=>delete m[0].content[0].id,emptyId:m=>m[0].content[0].id='',duplicateCall:m=>m[0].content.push(m[0].content[0]),duplicateResult:m=>m.push(m[1]),missingResult:m=>m.splice(1,1)}))test('native metadata result pairing refuses '+label,()=>{const m=nativeMessages();change(m);assert.throws(()=>findNativeMetadataResult(m,'text(1)'));});
